### ISSUE TITLE
Swap Node in Pairs

### ISSUE THREAD

**Issue by sayantan18kundu** [amanv8060/Leetcode-Questions#1726] opened 2021-10-01 06:10 UTC
Given a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list's nodes (i.e., only nodes themselves may be changed.)

Example 1:
Input: head = [1,2,3,4]
Output: [2,1,4,3]

**Comment by amanv8060** [comment] 2021-10-01 06:21
Can you specify Leetcode question number?

**Comment by amanv8060** [comment] 2021-10-01 09:26
Duplicate of #24

**Closed by amanv8060** 2021-10-01 09:26 UTC
